// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	CreatedAt    pgtype.Timestamptz
}

type VitaminCatalog struct {
	ID                    int64
	Code                  pgtype.Text
	DisplayName           string
	DefaultUnit           pgtype.Text
	InteractionText       pgtype.Text
	CompatibilityText     pgtype.Text
	ContraindicationsText pgtype.Text
	DefaultCondition      pgtype.Int2
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type UserVitamin struct {
	ID         int64
	UserID     int64
	CatalogID  pgtype.Int8
	Name       string
	DosageForm int16
	DoseValue  string
	DoseUnit   string
	Condition  int16
	Note       string
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type VitaminCourse struct {
	ID            int64
	UserVitaminID int64
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Timezone      string
	CreatedAt     pgtype.Timestamptz
}

type IntakeSchedule struct {
	ID        int64
	CourseID  int64
	Type      int16
	DaysMask  int16
	CreatedAt pgtype.Timestamptz
}

type IntakeTime struct {
	ID         int64
	ScheduleID int64
	TimeOfDay  pgtype.Time
	SortOrder  int32
}

type NotificationPreference struct {
	ID                       int64
	UserVitaminID            int64
	IncludeDose              bool
	IncludeFrequency         bool
	IncludeInteraction       bool
	IncludeCompatibility     bool
	IncludeCondition         bool
	IncludeContraindications bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type NotificationTextOverride struct {
	ID                            int64
	UserVitaminID                 int64
	InteractionTextOverride       pgtype.Text
	CompatibilityTextOverride     pgtype.Text
	ContraindicationsTextOverride pgtype.Text
}
