// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, first_name, last_name, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = $1,
    first_name = $2,
    last_name = $3
WHERE id = $4
RETURNING id, email, password_hash, first_name, last_name, created_at
`

type UpdateUserProfileParams struct {
	Email     string
	FirstName string
	LastName  string
	ID        int64
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Email, arg.FirstName, arg.LastName, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :execrows
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listVitaminCatalog = `-- name: ListVitaminCatalog :many
SELECT id, code, display_name, default_unit, interaction_text, compatibility_text,
       contraindications_text, default_condition, created_at, updated_at
FROM vitamin_catalog
ORDER BY display_name
`

func (q *Queries) ListVitaminCatalog(ctx context.Context) ([]VitaminCatalog, error) {
	rows, err := q.db.Query(ctx, listVitaminCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VitaminCatalog
	for rows.Next() {
		var i VitaminCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DisplayName,
			&i.DefaultUnit,
			&i.InteractionText,
			&i.CompatibilityText,
			&i.ContraindicationsText,
			&i.DefaultCondition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVitaminCatalogByID = `-- name: GetVitaminCatalogByID :one
SELECT id, code, display_name, default_unit, interaction_text, compatibility_text,
       contraindications_text, default_condition, created_at, updated_at
FROM vitamin_catalog
WHERE id = $1
`

func (q *Queries) GetVitaminCatalogByID(ctx context.Context, id int64) (VitaminCatalog, error) {
	row := q.db.QueryRow(ctx, getVitaminCatalogByID, id)
	var i VitaminCatalog
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.DefaultUnit,
		&i.InteractionText,
		&i.CompatibilityText,
		&i.ContraindicationsText,
		&i.DefaultCondition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserVitamin = `-- name: CreateUserVitamin :one
INSERT INTO user_vitamins (
    user_id, catalog_id, name, dosage_form, dose_value, dose_unit, condition, note, is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, catalog_id, name, dosage_form, dose_value, dose_unit, condition, note,
          is_active, created_at, updated_at
`

type CreateUserVitaminParams struct {
	UserID     int64
	CatalogID  pgtype.Int8
	Name       string
	DosageForm int16
	DoseValue  string
	DoseUnit   string
	Condition  int16
	Note       string
	IsActive   bool
}

func (q *Queries) CreateUserVitamin(ctx context.Context, arg CreateUserVitaminParams) (UserVitamin, error) {
	row := q.db.QueryRow(ctx, createUserVitamin,
		arg.UserID,
		arg.CatalogID,
		arg.Name,
		arg.DosageForm,
		arg.DoseValue,
		arg.DoseUnit,
		arg.Condition,
		arg.Note,
		arg.IsActive,
	)
	var i UserVitamin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CatalogID,
		&i.Name,
		&i.DosageForm,
		&i.DoseValue,
		&i.DoseUnit,
		&i.Condition,
		&i.Note,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserVitaminByID = `-- name: GetUserVitaminByID :one
SELECT id, user_id, catalog_id, name, dosage_form, dose_value, dose_unit, condition, note,
       is_active, created_at, updated_at
FROM user_vitamins
WHERE id = $1 AND user_id = $2
`

type GetUserVitaminByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetUserVitaminByID(ctx context.Context, arg GetUserVitaminByIDParams) (UserVitamin, error) {
	row := q.db.QueryRow(ctx, getUserVitaminByID, arg.ID, arg.UserID)
	var i UserVitamin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CatalogID,
		&i.Name,
		&i.DosageForm,
		&i.DoseValue,
		&i.DoseUnit,
		&i.Condition,
		&i.Note,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserVitamins = `-- name: ListUserVitamins :many
SELECT id, user_id, catalog_id, name, dosage_form, dose_value, dose_unit, condition, note,
       is_active, created_at, updated_at
FROM user_vitamins
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) ListUserVitamins(ctx context.Context, userID int64) ([]UserVitamin, error) {
	rows, err := q.db.Query(ctx, listUserVitamins, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserVitamin
	for rows.Next() {
		var i UserVitamin
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CatalogID,
			&i.Name,
			&i.DosageForm,
			&i.DoseValue,
			&i.DoseUnit,
			&i.Condition,
			&i.Note,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserVitaminCore = `-- name: UpdateUserVitaminCore :one
UPDATE user_vitamins
SET name = $1,
    dosage_form = $2,
    dose_value = $3,
    dose_unit = $4,
    condition = $5,
    note = $6,
    updated_at = now()
WHERE id = $7 AND user_id = $8
RETURNING id, user_id, catalog_id, name, dosage_form, dose_value, dose_unit, condition, note,
          is_active, created_at, updated_at
`

type UpdateUserVitaminCoreParams struct {
	Name       string
	DosageForm int16
	DoseValue  string
	DoseUnit   string
	Condition  int16
	Note       string
	ID         int64
	UserID     int64
}

func (q *Queries) UpdateUserVitaminCore(ctx context.Context, arg UpdateUserVitaminCoreParams) (UserVitamin, error) {
	row := q.db.QueryRow(ctx, updateUserVitaminCore,
		arg.Name,
		arg.DosageForm,
		arg.DoseValue,
		arg.DoseUnit,
		arg.Condition,
		arg.Note,
		arg.ID,
		arg.UserID,
	)
	var i UserVitamin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CatalogID,
		&i.Name,
		&i.DosageForm,
		&i.DoseValue,
		&i.DoseUnit,
		&i.Condition,
		&i.Note,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserVitaminActive = `-- name: UpdateUserVitaminActive :one
UPDATE user_vitamins
SET is_active = $1,
    updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, catalog_id, name, dosage_form, dose_value, dose_unit, condition, note,
          is_active, created_at, updated_at
`

type UpdateUserVitaminActiveParams struct {
	IsActive bool
	ID       int64
	UserID   int64
}

func (q *Queries) UpdateUserVitaminActive(ctx context.Context, arg UpdateUserVitaminActiveParams) (UserVitamin, error) {
	row := q.db.QueryRow(ctx, updateUserVitaminActive, arg.IsActive, arg.ID, arg.UserID)
	var i UserVitamin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CatalogID,
		&i.Name,
		&i.DosageForm,
		&i.DoseValue,
		&i.DoseUnit,
		&i.Condition,
		&i.Note,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVitaminCourse = `-- name: CreateVitaminCourse :one
INSERT INTO vitamin_courses (user_vitamin_id, start_date, end_date, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, user_vitamin_id, start_date, end_date, timezone, created_at
`

type CreateVitaminCourseParams struct {
	UserVitaminID int64
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Timezone      string
}

func (q *Queries) CreateVitaminCourse(ctx context.Context, arg CreateVitaminCourseParams) (VitaminCourse, error) {
	row := q.db.QueryRow(ctx, createVitaminCourse, arg.UserVitaminID, arg.StartDate, arg.EndDate, arg.Timezone)
	var i VitaminCourse
	err := row.Scan(
		&i.ID,
		&i.UserVitaminID,
		&i.StartDate,
		&i.EndDate,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getVitaminCourseByUserVitaminID = `-- name: GetVitaminCourseByUserVitaminID :one
SELECT id, user_vitamin_id, start_date, end_date, timezone, created_at
FROM vitamin_courses
WHERE user_vitamin_id = $1
`

func (q *Queries) GetVitaminCourseByUserVitaminID(ctx context.Context, userVitaminID int64) (VitaminCourse, error) {
	row := q.db.QueryRow(ctx, getVitaminCourseByUserVitaminID, userVitaminID)
	var i VitaminCourse
	err := row.Scan(
		&i.ID,
		&i.UserVitaminID,
		&i.StartDate,
		&i.EndDate,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const updateVitaminCourse = `-- name: UpdateVitaminCourse :one
UPDATE vitamin_courses
SET start_date = $1,
    end_date = $2,
    timezone = $3
WHERE user_vitamin_id = $4
RETURNING id, user_vitamin_id, start_date, end_date, timezone, created_at
`

type UpdateVitaminCourseParams struct {
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	Timezone      string
	UserVitaminID int64
}

func (q *Queries) UpdateVitaminCourse(ctx context.Context, arg UpdateVitaminCourseParams) (VitaminCourse, error) {
	row := q.db.QueryRow(ctx, updateVitaminCourse, arg.StartDate, arg.EndDate, arg.Timezone, arg.UserVitaminID)
	var i VitaminCourse
	err := row.Scan(
		&i.ID,
		&i.UserVitaminID,
		&i.StartDate,
		&i.EndDate,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const createIntakeSchedule = `-- name: CreateIntakeSchedule :one
INSERT INTO intake_schedules (course_id, type, days_mask)
VALUES ($1, $2, $3)
RETURNING id, course_id, type, days_mask, created_at
`

type CreateIntakeScheduleParams struct {
	CourseID int64
	Type     int16
	DaysMask int16
}

func (q *Queries) CreateIntakeSchedule(ctx context.Context, arg CreateIntakeScheduleParams) (IntakeSchedule, error) {
	row := q.db.QueryRow(ctx, createIntakeSchedule, arg.CourseID, arg.Type, arg.DaysMask)
	var i IntakeSchedule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.DaysMask,
		&i.CreatedAt,
	)
	return i, err
}

const getIntakeScheduleByCourseID = `-- name: GetIntakeScheduleByCourseID :one
SELECT id, course_id, type, days_mask, created_at
FROM intake_schedules
WHERE course_id = $1
`

func (q *Queries) GetIntakeScheduleByCourseID(ctx context.Context, courseID int64) (IntakeSchedule, error) {
	row := q.db.QueryRow(ctx, getIntakeScheduleByCourseID, courseID)
	var i IntakeSchedule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.DaysMask,
		&i.CreatedAt,
	)
	return i, err
}

const updateIntakeSchedule = `-- name: UpdateIntakeSchedule :one
UPDATE intake_schedules
SET type = $1,
    days_mask = $2
WHERE course_id = $3
RETURNING id, course_id, type, days_mask, created_at
`

type UpdateIntakeScheduleParams struct {
	Type     int16
	DaysMask int16
	CourseID int64
}

func (q *Queries) UpdateIntakeSchedule(ctx context.Context, arg UpdateIntakeScheduleParams) (IntakeSchedule, error) {
	row := q.db.QueryRow(ctx, updateIntakeSchedule, arg.Type, arg.DaysMask, arg.CourseID)
	var i IntakeSchedule
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Type,
		&i.DaysMask,
		&i.CreatedAt,
	)
	return i, err
}

const createIntakeTime = `-- name: CreateIntakeTime :one
INSERT INTO intake_times (schedule_id, time_of_day, sort_order)
VALUES ($1, $2, $3)
RETURNING id, schedule_id, time_of_day, sort_order
`

type CreateIntakeTimeParams struct {
	ScheduleID int64
	TimeOfDay  pgtype.Time
	SortOrder  int32
}

func (q *Queries) CreateIntakeTime(ctx context.Context, arg CreateIntakeTimeParams) (IntakeTime, error) {
	row := q.db.QueryRow(ctx, createIntakeTime, arg.ScheduleID, arg.TimeOfDay, arg.SortOrder)
	var i IntakeTime
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.TimeOfDay,
		&i.SortOrder,
	)
	return i, err
}

const listIntakeTimesByScheduleID = `-- name: ListIntakeTimesByScheduleID :many
SELECT id, schedule_id, time_of_day, sort_order
FROM intake_times
WHERE schedule_id = $1
ORDER BY sort_order, time_of_day
`

func (q *Queries) ListIntakeTimesByScheduleID(ctx context.Context, scheduleID int64) ([]IntakeTime, error) {
	rows, err := q.db.Query(ctx, listIntakeTimesByScheduleID, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntakeTime
	for rows.Next() {
		var i IntakeTime
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.TimeOfDay,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteIntakeTimesByScheduleID = `-- name: DeleteIntakeTimesByScheduleID :exec
DELETE FROM intake_times
WHERE schedule_id = $1
`

func (q *Queries) DeleteIntakeTimesByScheduleID(ctx context.Context, scheduleID int64) error {
	_, err := q.db.Exec(ctx, deleteIntakeTimesByScheduleID, scheduleID)
	return err
}

const createNotificationPreferences = `-- name: CreateNotificationPreferences :one
INSERT INTO notification_preferences (
    user_vitamin_id, include_dose, include_frequency, include_interaction,
    include_compatibility, include_condition, include_contraindications
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_vitamin_id, include_dose, include_frequency, include_interaction,
          include_compatibility, include_condition, include_contraindications,
          created_at, updated_at
`

type CreateNotificationPreferencesParams struct {
	UserVitaminID            int64
	IncludeDose              bool
	IncludeFrequency         bool
	IncludeInteraction       bool
	IncludeCompatibility     bool
	IncludeCondition         bool
	IncludeContraindications bool
}

func (q *Queries) CreateNotificationPreferences(ctx context.Context, arg CreateNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, createNotificationPreferences,
		arg.UserVitaminID,
		arg.IncludeDose,
		arg.IncludeFrequency,
		arg.IncludeInteraction,
		arg.IncludeCompatibility,
		arg.IncludeCondition,
		arg.IncludeContraindications,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserVitaminID,
		&i.IncludeDose,
		&i.IncludeFrequency,
		&i.IncludeInteraction,
		&i.IncludeCompatibility,
		&i.IncludeCondition,
		&i.IncludeContraindications,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationPreferencesByUserVitaminID = `-- name: GetNotificationPreferencesByUserVitaminID :one
SELECT id, user_vitamin_id, include_dose, include_frequency, include_interaction,
       include_compatibility, include_condition, include_contraindications,
       created_at, updated_at
FROM notification_preferences
WHERE user_vitamin_id = $1
`

func (q *Queries) GetNotificationPreferencesByUserVitaminID(ctx context.Context, userVitaminID int64) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferencesByUserVitaminID, userVitaminID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserVitaminID,
		&i.IncludeDose,
		&i.IncludeFrequency,
		&i.IncludeInteraction,
		&i.IncludeCompatibility,
		&i.IncludeCondition,
		&i.IncludeContraindications,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationPreferences = `-- name: UpdateNotificationPreferences :one
UPDATE notification_preferences
SET include_dose = $1,
    include_frequency = $2,
    include_interaction = $3,
    include_compatibility = $4,
    include_condition = $5,
    include_contraindications = $6,
    updated_at = now()
WHERE user_vitamin_id = $7
RETURNING id, user_vitamin_id, include_dose, include_frequency, include_interaction,
          include_compatibility, include_condition, include_contraindications,
          created_at, updated_at
`

type UpdateNotificationPreferencesParams struct {
	IncludeDose              bool
	IncludeFrequency         bool
	IncludeInteraction       bool
	IncludeCompatibility     bool
	IncludeCondition         bool
	IncludeContraindications bool
	UserVitaminID            int64
}

func (q *Queries) UpdateNotificationPreferences(ctx context.Context, arg UpdateNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, updateNotificationPreferences,
		arg.IncludeDose,
		arg.IncludeFrequency,
		arg.IncludeInteraction,
		arg.IncludeCompatibility,
		arg.IncludeCondition,
		arg.IncludeContraindications,
		arg.UserVitaminID,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserVitaminID,
		&i.IncludeDose,
		&i.IncludeFrequency,
		&i.IncludeInteraction,
		&i.IncludeCompatibility,
		&i.IncludeCondition,
		&i.IncludeContraindications,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationOverrides = `-- name: UpsertNotificationOverrides :one
INSERT INTO notification_text_overrides (
    user_vitamin_id, interaction_text_override, compatibility_text_override,
    contraindications_text_override
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_vitamin_id)
DO UPDATE SET interaction_text_override = EXCLUDED.interaction_text_override,
              compatibility_text_override = EXCLUDED.compatibility_text_override,
              contraindications_text_override = EXCLUDED.contraindications_text_override
RETURNING id, user_vitamin_id, interaction_text_override, compatibility_text_override,
          contraindications_text_override
`

type UpsertNotificationOverridesParams struct {
	UserVitaminID                 int64
	InteractionTextOverride       pgtype.Text
	CompatibilityTextOverride     pgtype.Text
	ContraindicationsTextOverride pgtype.Text
}

func (q *Queries) UpsertNotificationOverrides(ctx context.Context, arg UpsertNotificationOverridesParams) (NotificationTextOverride, error) {
	row := q.db.QueryRow(ctx, upsertNotificationOverrides,
		arg.UserVitaminID,
		arg.InteractionTextOverride,
		arg.CompatibilityTextOverride,
		arg.ContraindicationsTextOverride,
	)
	var i NotificationTextOverride
	err := row.Scan(
		&i.ID,
		&i.UserVitaminID,
		&i.InteractionTextOverride,
		&i.CompatibilityTextOverride,
		&i.ContraindicationsTextOverride,
	)
	return i, err
}

const getNotificationOverridesByUserVitaminID = `-- name: GetNotificationOverridesByUserVitaminID :one
SELECT id, user_vitamin_id, interaction_text_override, compatibility_text_override,
       contraindications_text_override
FROM notification_text_overrides
WHERE user_vitamin_id = $1
`

func (q *Queries) GetNotificationOverridesByUserVitaminID(ctx context.Context, userVitaminID int64) (NotificationTextOverride, error) {
	row := q.db.QueryRow(ctx, getNotificationOverridesByUserVitaminID, userVitaminID)
	var i NotificationTextOverride
	err := row.Scan(
		&i.ID,
		&i.UserVitaminID,
		&i.InteractionTextOverride,
		&i.CompatibilityTextOverride,
		&i.ContraindicationsTextOverride,
	)
	return i, err
}
