// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "vitamins-backend_2/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// ServiceAPI is an autogenerated mock type for the ServiceAPI type
type ServiceAPI struct {
	mock.Mock
}

// ConfirmPasswordChange provides a mock function with given fields: ctx, changeToken, password, passwordConfirm
func (_m *ServiceAPI) ConfirmPasswordChange(ctx context.Context, changeToken string, password string, passwordConfirm string) error {
	ret := _m.Called(ctx, changeToken, password, passwordConfirm)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPasswordChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, changeToken, password, passwordConfirm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmPasswordReset provides a mock function with given fields: ctx, resetToken, password, passwordConfirm
func (_m *ServiceAPI) ConfirmPasswordReset(ctx context.Context, resetToken string, password string, passwordConfirm string) error {
	ret := _m.Called(ctx, resetToken, password, passwordConfirm)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, resetToken, password, passwordConfirm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *ServiceAPI) GetProfile(ctx context.Context, userID int64) (auth.UserProfile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 auth.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (auth.UserProfile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) auth.UserProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(auth.UserProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, email, pw
func (_m *ServiceAPI) Login(ctx context.Context, email string, pw string) (*auth.TokenPair, error) {
	ret := _m.Called(ctx, email, pw)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*auth.TokenPair, error)); ok {
		return rf(ctx, email, pw)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *auth.TokenPair); ok {
		r0 = rf(ctx, email, pw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, pw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refresh provides a mock function with given fields: ctx, token
func (_m *ServiceAPI) Refresh(ctx context.Context, token string) (*auth.TokenPair, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *auth.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.TokenPair, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.TokenPair); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, email, pw
func (_m *ServiceAPI) Register(ctx context.Context, email string, pw string) (*auth.TokenPair, error) {
	ret := _m.Called(ctx, email, pw)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*auth.TokenPair, error)); ok {
		return rf(ctx, email, pw)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *auth.TokenPair); ok {
		r0 = rf(ctx, email, pw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, pw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestPasswordChange provides a mock function with given fields: ctx, userID
func (_m *ServiceAPI) RequestPasswordChange(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestPasswordReset provides a mock function with given fields: ctx, email
func (_m *ServiceAPI) RequestPasswordReset(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProfile provides a mock function with given fields: ctx, userID, in
func (_m *ServiceAPI) UpdateProfile(ctx context.Context, userID int64, in auth.ProfileUpdate) (auth.UserProfile, error) {
	ret := _m.Called(ctx, userID, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 auth.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, auth.ProfileUpdate) (auth.UserProfile, error)); ok {
		return rf(ctx, userID, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, auth.ProfileUpdate) auth.UserProfile); ok {
		r0 = rf(ctx, userID, in)
	} else {
		r0 = ret.Get(0).(auth.UserProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, auth.ProfileUpdate) error); ok {
		r1 = rf(ctx, userID, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyPasswordChangeCode provides a mock function with given fields: ctx, userID, code
func (_m *ServiceAPI) VerifyPasswordChangeCode(ctx context.Context, userID int64, code string) (string, error) {
	ret := _m.Called(ctx, userID, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPasswordChangeCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (string, error)); ok {
		return rf(ctx, userID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) string); ok {
		r0 = rf(ctx, userID, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyPasswordResetCode provides a mock function with given fields: ctx, email, code
func (_m *ServiceAPI) VerifyPasswordResetCode(ctx context.Context, email string, code string) (string, error) {
	ret := _m.Called(ctx, email, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPasswordResetCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServiceAPI creates a new instance of ServiceAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAPI {
	mock := &ServiceAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
